/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haier_controler_api_SerialPort */

#ifndef _Included_com_haier_controler_api_SerialPort
#define _Included_com_haier_controler_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haier_controler_api_SerialPort
 * Method:    SerialOpen
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_haier_controler_api_SerialPort_SerialOpen
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_haier_controler_api_SerialPort
 * Method:    SerialClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_haier_controler_api_SerialPort_SerialClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
